### ISSUE TITLE
General - Convert Error/Success Messages to Bootstrap Toasts

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/NER-PM-Dashboard#32]
Currently, when there are error/success messages, the page automatically scrolls to the top to display the message to the user. Although this allows the user to see the error/success messages, it is not the optimal solution as the user has to scroll back to where they were in the page after they finish viewing the message. 

James' comment from #26: Alternative solution: convert error and success messaging within the application to [Bootstrap toasts](https://getbootstrap.com/docs/4.3/components/toasts/) that are positioned as an overlay, relative to the screen instead of fixed to the page, still dismissible, and also potentially auto-hiding after a set period of time.

Real-world usage of toasts in LinkedIn (again from James' comment in #26):
![image](https://user-images.githubusercontent.com/51571627/97392574-56334780-189f-11eb-9e01-94f1e74a6739.png)

**Comment by RahulR100** [comment]
I think for this its possible to make the alert float on the top of the website, there are some bootstrap classes we can use for that. I think this is better because alerts suggest to the user that something has gone wrong, a critical error in the application, whereas a toast is usually used for suggesting non critical events or action confirmations (such as the one in the picture)

**Comment by RahulR100** [comment]
Alerts have now been changed to use floating alerts instead of toasts.

<img width="1784" alt="Screenshot 2020-12-22 at 5 51 22 PM" src="https://user-images.githubusercontent.com/29384660/102941606-0d68cb00-44ab-11eb-92b1-809e64191d17.png">
